"""Add cascade deletes to ad/conversation/message

Revision ID: 22cf714f2b65
Revises: dc02599d7813
Create Date: 2025-07-02 04:13:21.886089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cf714f2b65'
down_revision = 'dc02599d7813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ad_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_ad_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_seller_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_buyer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ad', ['ad_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['seller_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['buyer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('image_ad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ad', ['ad_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_conversation_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rating_reviewed_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rating_reviewer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rating_ad_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['reviewer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'ad', ['ad_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rating_ad_id_fkey'), 'ad', ['ad_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('rating_reviewer_id_fkey'), 'user', ['reviewer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('rating_reviewed_id_fkey'), 'user', ['reviewed_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_sender_id_fkey'), 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('message_conversation_id_fkey'), 'conversation', ['conversation_id'], ['id'])

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('image_ad_id_fkey'), 'ad', ['ad_id'], ['id'])

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_buyer_id_fkey'), 'user', ['buyer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_seller_id_fkey'), 'user', ['seller_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_ad_id_fkey'), 'ad', ['ad_id'], ['id'])

    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ad_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
