"""Add profile_pic column to User

Revision ID: 478678a32159
Revises: 
Create Date: 2025-06-20 21:17:07.968375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478678a32159'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
