"""Add is_verified field to User

Revision ID: 6f5192a03d4f
Revises: a5351104337d
Create Date: 2025-06-22 00:50:33.092063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5192a03d4f'
down_revision = 'a5351104337d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
