"""Add Conversation and Message tables with ad_id column

Revision ID: ad71389dc514
Revises: 478678a32159
Create Date: 2025-06-21 04:54:36.897092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad71389dc514'
down_revision = '478678a32159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_convo_ad_id', 'ad', ['ad_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ad_id')

    # ### end Alembic commands ###
